/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    DomainCard: typeof import('./src/components/DomainCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FilterSidebar: typeof import('./src/components/FilterSidebar.vue')['default']
    GradeCard: typeof import('./src/components/GradeCard.vue')['default']
    LinkedPatentList: typeof import('./src/components/LinkedPatentList.vue')['default']
    MatchTable: typeof import('./src/components/MatchTable.vue')['default']
    PatentStatusTag: typeof import('./src/components/PatentStatusTag.vue')['default']
    PerformanceRadar: typeof import('./src/components/PerformanceRadar.vue')['default']
    PlaceholderLinks: typeof import('./src/components/PlaceholderLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioCard: typeof import('./src/components/ScenarioCard.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TagChip: typeof import('./src/components/TagChip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
