/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    DomainCard: typeof import('./src/components/DomainCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FilterSidebar: typeof import('./src/components/FilterSidebar.vue')['default']
    GradeCard: typeof import('./src/components/GradeCard.vue')['default']
    MatchTable: typeof import('./src/components/MatchTable.vue')['default']
    PerformanceRadar: typeof import('./src/components/PerformanceRadar.vue')['default']
    PlaceholderLinks: typeof import('./src/components/PlaceholderLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioCard: typeof import('./src/components/ScenarioCard.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TagChip: typeof import('./src/components/TagChip.vue')['default']
  }
}
